import type { Metadata } from 'next'
import './globals.css'
import { Roboto } from 'next/font/google'
import { ChildProps } from '@/types'
import { ThemeProvider } from '@/components/providers/theme-provider'
import { dir } from 'i18next'

const languages = ['en', 'ru', 'uz']

const roboto = Roboto({
	subsets: ['latin'],
	weight: ['500', '700', '800'],
	variable: '--font-roboto',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export async function generateStaticParams() {
	return languages.map(lng => ({ lng }))
}

interface Props extends ChildProps {
	params: { lng: string }
}

export default function RootLayout({ children, params: { lng } }: Props) {
	return (
		<html lang={lng} dir={dir(lng)} suppressHydrationWarning>
			<body className={`${roboto.variable} antialiased overflow-x-hidden`}>
				<ThemeProvider
					attribute='class'
					defaultTheme='system'
					enableSystem
					disableTransitionOnChange
				>
					{children}
				</ThemeProvider>
			</body>
		</html>
	)
}
